name: Build and Release

on:
  push:
    tags:
      - "v*"
    branches:
      - "release"

jobs:
  build:
    name: Build Binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Determine Version
        id: version
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}  # Get version from tag
          else
            VERSION=dev-${GITHUB_SHA::8}     # Use short SHA for branch-based
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Version is $VERSION"

      - name: Install Dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get -y install clang make
        # No need to install dependencies on macOS and Windows since Clang/make are built-in or pre-installed

      - name: Build Binary
        run: |
          OS=$(uname | tr '[:upper:]' '[:lower:]')  # Detect OS
          ARCH=$(uname -m)                          # Detect architecture
          mkdir -p dist                             # Create output directory
          make EXE=chimp-${VERSION}-${OS}-${ARCH}
          mv chimp-${VERSION}-${OS}-${ARCH} dist/

      - name: Archive Binary
        run: |
          cd dist
          zip chimp-${VERSION}-${{ matrix.os }}-${ARCH}.zip chimp-${VERSION}-${{ matrix.os }}-${ARCH}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: chimp-${{ matrix.os }}-${ARCH}-${{ env.VERSION }}
          path: dist/chimp-${VERSION}-${{ matrix.os }}-${ARCH}.zip

  release:
    needs: build
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "Chimp ${{ github.event.ref_name || env.VERSION }}"
          body: |
            Automated release of Chimp ${{ github.event.ref_name || env.VERSION }}.
            This release includes binaries for:
            - Linux
            - macOS
            - Windows
          files: dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
